version: "3.8"

services:
  chatbot-database:
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=deployment
      - CHATBOT_URL: ${{ secrets.CHATBOT_URL }}
      - DB_SERVICE_URL: ${{ secrets.DB_SERVICE_URL }}
      - TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    restart: always
